name: stargaze_kyc_sdk
description: KYC
version: 0.0.1+1

environment:
  sdk: 2.18.1
  flutter: 3.3.2

dependencies:
  flutter:
    sdk: flutter

  # http
  http: 0.13.5
  intl: 0.17.0

  # DI
  injectable: 1.5.4
  get_it: 7.2.0

  json_serializable: 6.5.4
  ml_linalg: 13.10.0

dependency_overrides:
  analyzer: 4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  test: any

  mockito: 5.3.1

  flutter_lints: 2.0.1
  injectable_generator: 1.5.4
