name: stargaze_kyc_sdk
description: KYC
version: 0.0.1+1

environment:
  sdk: 2.18.1
  flutter: 3.3.2

dependencies:
  flutter:
    sdk: flutter

  # http
  http: 0.13.5
  intl: 0.17.0

  # DI
  injectable: 1.5.3
  get_it: 7.2.0

  json_serializable: ^6.1.4
  #numdart: 1.0.0
  scidart: ^0.0.2-dev.12

  # MobX
#  mobx: 2.1.1
#  flutter_mobx: 2.0.6+4

  # image picker
#  image_picker: 0.8.5+3

#  # General
#  image: 3.2.0
#  path_provider: 2.0.11
#  native_exif: 0.4.0

dependency_overrides:
  #analyzer: 5.2.0
#  test_api: 0.4.15
#  matcher: 0.12.13
#  xml: 5.0.0
#  camera: 0.10.0+1
#  image: 3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  test: any

  mockito: 5.3.1

  flutter_lints: 2.0.1

  # MobX

#  mobx_codegen: 2.0.7+3
  injectable_generator: 1.5.4
